import { Injectable } from '@angular/core';
import { QrPayload } from '../models/qr-payload.model';

export interface ValidationResult { valid: boolean; error?: string; payload?: QrPayload; }

@Injectable({ providedIn: 'root' })
export class ValidationService {
  validatePayload(value: unknown): ValidationResult {
    if (!value || typeof value !== 'object') return this.invalid();
    const p = value as Record<string, unknown>;
    const strings = ['app', 'algorithm', 'kdf', 'salt', 'iv', 'ciphertext', 'createdAt', 'messageId'];
    if (strings.some((key) => typeof p[key] !== 'string' || !p[key])) return this.invalid();
    if (p['app'] !== 'QRSecure') return { valid: false, error: 'This QR code was not generated by QRSecure.' };
    if (p['version'] !== 1 || p['algorithm'] !== 'AES-GCM' || p['kdf'] !== 'PBKDF2') return this.invalid();
    if (!Number.isInteger(p['iterations']) || (p['iterations'] as number) < 100_000) return this.invalid();
    try { atob(p['salt'] as string); atob(p['iv'] as string); atob(p['ciphertext'] as string); } catch { return this.invalid(); }
    const payload = p as unknown as QrPayload;
    if (payload.expiresAt && new Date(payload.expiresAt).getTime() <= Date.now()) {
      return { valid: false, error: 'This encrypted message has expired.' };
    }
    return { valid: true, payload };
  }

  parsePayload(raw: string): ValidationResult {
    try { return this.validatePayload(JSON.parse(raw)); } catch { return this.invalid(); }
  }

  private invalid(): ValidationResult { return { valid: false, error: 'Invalid Secure QR Code.' }; }
}
