import { describe, expect, it } from 'vitest';
import { ValidationService } from './validation.service';

describe('ValidationService', () => {
  const service = new ValidationService();
  const valid = { app: 'QRSecure', version: 1, algorithm: 'AES-GCM', kdf: 'PBKDF2', iterations: 310000, salt: 'MTIzNA==', iv: 'MTIzNA==', ciphertext: 'MTIzNA==', createdAt: new Date().toISOString(), expiresAt: null, oneTime: false, messageId: 'test-id' };

  it('accepts a supported QRSecure payload', () => expect(service.validatePayload(valid).valid).toBe(true));
  it('rejects another application identifier', () => expect(service.validatePayload({ ...valid, app: 'Other' }).error).toBe('This QR code was not generated by QRSecure.'));
  it('safely rejects malformed JSON', () => expect(service.parsePayload('{bad').valid).toBe(false));
  it('rejects expired messages', () => expect(service.validatePayload({ ...valid, expiresAt: '2020-01-01T00:00:00.000Z' }).error).toBe('This encrypted message has expired.'));
});
